/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "google_auth.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(MigrationPayload, MigrationPayload, AUTO)


PB_BIND(MigrationPayload_OtpParameters, MigrationPayload_OtpParameters, AUTO)





